services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    volumes:
      # Mounts your local code into the container
      - ./frontend:/app
      # Creates a separate volume for node_modules to avoid being overwritten
      - frontend_node_modules:/app/node_modules
    # Overrides the Dockerfile's CMD to run the dev server
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-}
      - BIGTABLE_INSTANCE=${BIGTABLE_INSTANCE:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    volumes:
      # Mounts your local code into the container for hot-reloading
      - ./backend:/app
    # The command is set in the Dockerfile.dev

# Defines the named volume for the frontend's node_modules
volumes:
  frontend_node_modules:
